#!/usr/bin/env python3
"""Update Colombian holidays configuration from the holidays library.

This script generates/updates config/holidays.yaml with official Colombian
holidays for the specified years. Uses the `holidays` Python library which
includes proper handling of "observed" holidays (Ley Emiliani - movable holidays).

Usage:
    python scripts/update_holidays.py              # Update for current + next year
    python scripts/update_holidays.py --years 2025 2026 2027  # Specific years
"""

import argparse
import sys
from datetime import date
from pathlib import Path

try:
    import holidays
except ImportError:
    print("Error: 'holidays' library not installed.")
    print("Install with: pip install holidays")
    sys.exit(1)

import yaml


def get_colombian_holidays(years: list[int]) -> dict[int, list[dict]]:
    """Get Colombian holidays for specified years.

    Args:
        years: List of years to get holidays for.

    Returns:
        Dictionary mapping year to list of holiday dicts with date and name.
    """
    co_holidays = holidays.Colombia(years=years)

    result: dict[int, list[dict]] = {}

    for holiday_date, name in sorted(co_holidays.items()):
        year = holiday_date.year
        if year not in result:
            result[year] = []

        result[year].append({
            "date": holiday_date.isoformat(),
            "name": name,
        })

    return result


def update_holidays_yaml(
    holidays_data: dict[int, list[dict]],
    output_path: Path,
) -> None:
    """Write holidays data to YAML file.

    Args:
        holidays_data: Dictionary of holidays by year.
        output_path: Path to output YAML file.
    """
    # Convert to the expected format
    yaml_data = {"holidays": {}}

    for year, holiday_list in sorted(holidays_data.items()):
        yaml_data["holidays"][year] = holiday_list

    # Write with nice formatting
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Colombian Holidays Configuration\n")
        f.write("# Auto-generated by scripts/update_holidays.py\n")
        f.write("# Source: holidays Python library (https://pypi.org/project/holidays/)\n")
        f.write("# Includes 'observed' holidays per Ley Emiliani (movable to Monday)\n")
        f.write("#\n")
        f.write(f"# Last updated: {date.today().isoformat()}\n")
        f.write(f"# Years: {', '.join(str(y) for y in sorted(holidays_data.keys()))}\n")
        f.write("\n")
        yaml.dump(
            yaml_data,
            f,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
        )

    print(f"Updated: {output_path}")
    print(f"Years: {sorted(holidays_data.keys())}")

    total = sum(len(h) for h in holidays_data.values())
    print(f"Total holidays: {total}")


def main() -> None:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Update Colombian holidays configuration"
    )
    parser.add_argument(
        "--years",
        nargs="+",
        type=int,
        default=None,
        help="Years to include (default: current year + next year)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("config/holidays.yaml"),
        help="Output YAML file path",
    )
    parser.add_argument(
        "--preview",
        action="store_true",
        help="Preview holidays without writing file",
    )

    args = parser.parse_args()

    # Default: current year + next year
    if args.years is None:
        current_year = date.today().year
        args.years = [current_year, current_year + 1]

    print(f"Fetching Colombian holidays for years: {args.years}")

    holidays_data = get_colombian_holidays(args.years)

    if args.preview:
        print("\nPreview of holidays:")
        print("-" * 50)
        for year, holiday_list in sorted(holidays_data.items()):
            print(f"\n{year}:")
            for h in holiday_list:
                print(f"  {h['date']}: {h['name']}")
        return

    update_holidays_yaml(holidays_data, args.output)


if __name__ == "__main__":
    main()
